#! /bin/sh

sxhkd &

bspc monitor DVI-D-0 -d 1 2 3 4 5
#6 7 8 9 0

bspc config border_width		2
bspc config window_gap			6

bspc config split_ratio			0.52
bspc config borderless_monocle	true
bspc config gapless_monocle		true
bspc config click_to_focus		true

## Colores
bspc config active_border_color     '#29adff'
bspc config focused_border_color     '#29adff'
bspc config normal_border_color     '#282a2e'
bspc config presel_border_color     '#0f8c61'
bspc config urgent_border_color     '#922230'

## Ventanas y espacios
# Asignar ventanas a espacios
#bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Google-chrome-unstable desktop=^2
bspc rule -a "Firefox Beta" desktop=^3
bspc rule -a Geany desktop=^4
bspc rule -a Spotify desktop=^5
bspc rule -a discord desktop=^6
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
# Ventanas flotantes
bspc rule -a mpv state=floating
bspc rule -a Thunar state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a feh state=floating
bspc rule -a Viewnior state=floating
bspc rule -a File-roller state=floating
bspc rule -a lxappearance state=floating
bspc rule -a obconf state=floating
bspc rule -a nvidia-settings state=floating


## Inicio de aplicaciones
# Establecer puntero
xsetroot -cursor_name left_ptr &
# Cargar ajustes de Xresources
xrdb -merge ~/.Xresources &
# Cargar ajustes de nvidia-settings
nvidia-settings --load-config-only &
# Establecer fondo de pantalla
~/.fehbg &
# Encender teclado
xset led 3 &
# Iniciar compton
compton &
# Iniciar dunst
dunst &
# Iniciar dzen2
dzen2 &
# Iniciar polybar
#polybar top &
~/.config/polybar/launch.sh 2 &
# Iniciar Dropbox con dropbox-cli
sleep 30s && dropbox-cli start &
